spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myjava
    username: root
    password: wl624528405wang
    driver-class-name: com.mysql.cj.jdbc.Driver
  http:
    encoding:
      charset: utf-8
server:
  port: 8080
